source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "8.0"


target :'KSJC' do

pod 'AMap3DMap'
#pod 'XAspect', '~> 1.0.5'
pod 'MJExtension', '~> 3.0.13'
#pod 'LSYShowController'
pod 'LSYXAspect'
end
